name: 'Terraform'

on:
  push:
    paths:
      - 'terraform/*.tf'
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    env:
      TF_VAR_ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      TF_VAR_ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      TF_VAR_AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      TF_VAR_MVP_SUBSCRIPTION: ${{ secrets.MVP_SUBSCRIPTION }}
      TF_LOG: DEBUG

    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3

      - name: Terraform Init
        run: |
          cd terraform
          terraform init  

      - name: Terraform Plan
        run: |
          cd terraform
          terraform plan -refresh=false
        timeout-minutes: 30

      - name: Terraform Apply
        run: |
          cd terraform
          terraform apply -auto-approve
        timeout-minutes: 30
